routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PagesController@index')->name('home');
Route::get('/about', 'PagesController@about')->name('about');
Route::get('/donations', 'PagesController@donations')->name('donations');
Route::get('/join', 'PagesController@join')->name('join')->middleware('guest');

Route::get('/contacts', function () {
    return view('contacts');
})->name('contacts');

Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/suspended', 'UserController@suspended');
Route::get('emailverification/{token}', 'UserController@emailverify')->name('emailverify.index')->middleware('guest');
Route::post('emailverification/{token}', 'UserController@emailverifyupdate')->name('emailverify.store')->middleware('guest');
Route::get('membershippayment/{memberid}', 'UserController@membershipPayment')->name('membershippayment');

Auth::routes();

Route::group(['prefix' => 'administrator', 'middleware' => ['auth', 'checkadmin' ], 'as'=>'administrator.'], function () {
	Route::get('/', 'AdminController@index')->name('dashboard');
	Route::group(['prefix' => 'users', 'as'=>'users.'], function () {
		Route::get('single/{id}/projects', 'AdminController@singleUser')->name('single');
		Route::get('single/{id}/trasactions', 'AdminController@singleUsertrasactions')->name('transactions');
		Route::get('single/{id}/profile', 'AdminController@singleUserprofile')->name('profile');
		Route::get('single/{id}/membership', 'AdminController@singleUsermembership')->name('membership');
		Route::get('single/{id}/commisions', 'AdminController@singleUsercommisions')->name('commisions');
		Route::get('single/{id}/banking', 'AdminController@singleUserbanking')->name('banking');
		Route::get('table', 'AdminController@alluserstable')->name('table');
		Route::get('chart', 'AdminController@alluserschart')->name('chart');
	});
	Route::group(['prefix' => 'permisions', 'as'=>'permisions.'], function () {
		Route::get('single/{id}', 'AdminController@singlePermision')->name('single');
		Route::get('table', 'AdminController@allpermisions')->name('all');
		Route::post('addroleuser', 'AdminController@addUserRole')->name('adduserrole');
		Route::post('removeroleuser/{userid}/{roleid}', 'AdminController@removeRoleUser')->name('removeroleuser');
	});

	Route::group(['prefix' => 'projects', 'as'=>'projects.'], function () {
		Route::get('single/{id}', 'AdminController@singleProject')->name('single');
		Route::get('table', 'AdminController@allprojects')->name('all');
		Route::get('chart', 'AdminController@allprojectschart')->name('chart');
		Route::get('single/{id}/donations', 'AdminController@viewprojectdonations')->name('projectdonations');
		Route::get('single/{id}/messages', 'AdminController@viewprojectmessages')->name('projectmessages');
		Route::get('single/{id}/settings', 'AdminController@viewprojectsettings')->name('projectsettings');
		Route::get('single/{id}/stats', 'AdminController@viewprojectstats')->name('projectstats');
	});

	Route::group(['prefix' => 'events', 'as'=>'events.'], function () {
		Route::get('single/{id}/view', 'AdminController@singleEvent')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singleEventEdit')->name('edit');
		Route::get('table', 'AdminController@alleventstable')->name('all');
		Route::get('chart', 'AdminController@alleventschart')->name('chart');
		Route::get('new', 'AdminController@newevent')->name('new');
	});

	Route::group(['prefix' => 'blog', 'as'=>'blog.'], function () {
		Route::get('single/{id}/view', 'AdminController@singlePost')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singlePostEdit')->name('edit');
		Route::get('table', 'AdminController@allblogposts')->name('all');
		Route::get('chart', 'AdminController@allblogpostschart')->name('chart');
		Route::get('new', 'AdminController@newblogpost')->name('new');
	});

	Route::group(['prefix' => 'payments', 'as'=>'payments.'], function () {
		Route::get('all', 'AdminController@allPaymentsreceived')->name('allreceived');
		Route::get('single/{id}', 'AdminController@singlePaymentreceivedTrans')->name('single');
	});

	Route::group(['prefix' => 'faqs', 'as'=>'faqs.'], function () {
		Route::get('all', 'AdminController@allFaqs')->name('all');
		Route::get('single/{id}/view', 'AdminController@singleFaq')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singleFaqEdit')->name('edit');
		Route::get('new', 'AdminController@createFaq')->name('new');
	});

	Route::group(['prefix' => 'rules', 'as'=>'rules.'], function () {
		Route::get('all', 'AdminController@allRules')->name('all');
		Route::get('single/{id}/view', 'AdminController@singleRules')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singleRulesEdit')->name('edit');
		Route::get('new', 'AdminController@createRules')->name('new');
	});

	Route::group(['prefix' => 'pages', 'as'=>'pages.'], function () {
		Route::get('homepage', 'AdminController@homepageSetings')->name('homepage');
		Route::get('about', 'AdminController@aboutSetings')->name('about');
		Route::get('generalsettings', 'AdminController@generalSettings')->name('generalsettings');
	});

});

Route::group(['prefix' => 'datatables', 'middleware' => ['auth', 'checkadmin' ], 'as'=>'datatables.'], function () {
	Route::any('newusers', 'DatatableController@newusers')->name('newusers');
	Route::any('allusers', 'DatatableController@allusers')->name('allusers');
	Route::any('allpermisions', 'DatatableController@allpermisions')->name('allpermisions');
	Route::any('singlepermision/{id}', 'DatatableController@singlePermision')->name('singlepermision');
	Route::any('allprojects', 'DatatableController@allprojects')->name('allprojects');
	Route::any('allevents', 'DatatableController@allevents')->name('allevents');
	Route::any('allposts', 'DatatableController@allposts')->name('allposts');
	Route::any('allpaymentsreceived', 'DatatableController@allpaymentsreceived')->name('allpaymentsreceived');
	Route::any('allfaqs', 'DatatableController@allfaqs')->name('allfaqs');
	Route::any('allrules', 'DatatableController@allrules')->name('allrules');
	Route::any('testmonials', 'DatatableController@testmonials')->name('testmonials');
	Route::any('slider', 'DatatableController@settingSlider')->name('settingslider');
	Route::any('sponsors', 'DatatableController@settingSponsors')->name('sponsors');
	Route::any('founders', 'DatatableController@founders')->name('founders');
	Route::post('deleteslider', 'DatatableController@deleteSlider')->name('deleteslider');
	Route::post('deletesponsor', 'DatatableController@deleteSponsor')->name('deletesponsor');
	Route::post('deletetestmonial', 'DatatableController@deleteTestmonial')->name('deletetestmonial');
	Route::post('deletefounder', 'DatatableController@deleteFounder')->name('deletefounder');
});

Route::group(['prefix' => 'chartdata', 'middleware' => ['auth', 'checkadmin' ], 'as'=>'chartdata.'], function () {
	Route::any('usersvsmonth', 'ChartController@usersVsMonth')->name('usersvsmonth');
	Route::any('projectsvsmonth', 'ChartController@projectsVsmonth')->name('projectsvsmonth');
	Route::any('eventsvsmonth', 'ChartController@eventsVsmonth')->name('eventsvsmonth');
	Route::any('postsvsmonth', 'ChartController@postsVsmonth')->name('postsvsmonth');
});

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::get('createproject', 'HomeController@createproject')->name('createproject');
    Route::get('myproject/{id}/view', 'HomeController@viewproject')->name('myproject');
    Route::get('myproject/{id}/donations', 'HomeController@viewprojectdonations')->name('myprojectdonations');
    Route::get('myproject/{id}/messages', 'HomeController@viewprojectmessages')->name('myprojectmessages');
    Route::get('myproject/{id}/messages/{comment}', 'HomeController@viewprojectmessagescomments')->name('viewprojectmessagescomments');
    Route::get('myproject/{id}/settings', 'HomeController@viewprojectsettings')->name('myprojectsettings');
    Route::get('myproject/{id}/stats', 'HomeController@viewprojectstats')->name('myprojectstats');
    Route::get('myprojects', 'HomeController@viewprojects')->name('myprojects');
    Route::get('mycontributions', 'HomeController@mycontributions')->name('mycontributions');
    Route::get('mydonations', 'HomeController@mydonations')->name('mydonations');
    Route::get('mymessages', 'HomeController@mymessages')->name('mymessages');
    Route::group(['prefix' => 'profile', 'as'=>'profile.'], function () {
		Route::get('/', 'HomeController@myProfile')->name('index');
	});

	Route::group(['as'=>'dash.'], function () {
		Route::get('transactions', 'HomeController@myTransactions')->name('transactions');
		Route::get('membership', 'HomeController@myMembership')->name('membership');
		Route::get('commisions', 'HomeController@myCommisions')->name('commisions');
		Route::get('banking', 'HomeController@myBanking')->name('banking');
	});

	Route::group(['prefix' => 'chartdata', 'as'=>'analytics.'], function () {
		Route::any('donationsvsmonth/{id}', 'ChartController@donationsVsmonth')->name('donations');
	});

});

Route::get('projects/{id}/messages', 'ProjectController@projectmessages')->name('projectmessages');
// Route::get('projects/{id}/donations', 'ProjectController@projectdonations')->name('projectdonations');
Route::any('mailboxes/{id}/sent', 'MailboxController@sentmail')->name('mailboxes.sentmail');
Route::any('mailboxes/{id}/inbox', 'MailboxController@inboxmail')->name('mailboxes.inboxmail');

Route::resource('photos', 'ImageController');

resources/views/partials/aboutfounders.blade.php
<div class="column is-3">
	<div class="card">
	  <div class="card-image">
		<figure class="image is-4by3">
			<img src="{{ asset('storage/'.$founder->image->name) }}" alt="">
		</figure>
	  </div>
	  <div class="card-content">
		  <p class="title is-4 has-text-centered">{{ $founder->name }}</p>
		  <div class="field  has-addons is-grouped has-addons-centered">
			<p class="control">
			  <a href="{{ $founder->facebook }}"  class="button">
				<span class="icon is-medium">
				  <i class="fa fa-facebook"></i>
				</span>
			  </a>
			</p>
			<p class="control">
				<a href="{{ $founder->twitter }}"  class="button">
					<span class="icon is-medium">
					  <i class="fa fa-twitter"></i>
					</span>
				</a>
			</p>
		  </div>
	  </div>

	</div>

</div>

resources/views/partials/adminmenu.blade.php
<aside class="menu">
	<p class="menu-label">General</p>
  <ul class="menu-list">
    <li><a class=" {{{ (Route::is('administrator.dashboard') ? 'is-active' : '') }}} " href="{{ route('administrator.dashboard')}}">Dashboard</a></li>
  </ul>
  <p class="menu-label">User Manager</p>
   <ul class="menu-list">
    <li><a class=" {{{ ( (Route::is('administrator.users.table') || Route::is('administrator.users.chart') ) ? 'is-active' : '') }}} " href="{{ route('administrator.users.table')}}">All Users</a></li>
    <li><a class=" {{{ (Route::is('administrator.permisions.all') ? 'is-active' : '') }}} " href="{{ route('administrator.permisions.all')}}">Permisions</a></li>
  </ul>
  <p class="menu-label">Projects Manager</p>
  <ul class="menu-list">
    <li><a class=" {{{ ( (Route::is('administrator.projects.all') || Route::is('administrator.projects.chart')  || Route::is('administrator.projects.single')) ? 'is-active' : '') }}} "  href="{{ route('administrator.projects.all')}}">All Projects</a></li>
  </ul>
  <p class="menu-label"> Transactions Manager</p>
  <ul class="menu-list">
	<li><a class=" {{{ ( Route::is('administrator.payments.allreceived') ? 'is-active' : '') }}} " href="{{ route('administrator.payments.allreceived')}}">Payments Received</a></li>

  </ul>
  <p class="menu-label"> Events Manager</p>
  <ul class="menu-list">
    <li><a class=" {{{ ( (Route::is('administrator.events.all') || Route::is('administrator.events.chart')) ? 'is-active' : '') }}} " href="{{ route('administrator.events.all')}}">All Events</a></li>
    <li><a class=" {{{ (Route::is('administrator.events.new') ? 'is-active' : '') }}} " href="{{ route('administrator.events.new')}}">New Event</a></li>
  </ul>
  <p class="menu-label"> Blog Manager</p>
  <ul class="menu-list">
     <li><a class=" {{{ ( (Route::is('administrator.blog.all') || Route::is('administrator.blog.chart')) ? 'is-active' : '') }}} " href="{{ route('administrator.blog.all')}}">All Posts</a></li>
    <li><a class=" {{{ (Route::is('administrator.blog.new') ? 'is-active' : '') }}} " href="{{ route('administrator.blog.new')}}">New Post</a></li>
  </ul>
  <p class="menu-label"> Faq Manager</p>
  <ul class="menu-list">
     <li><a class=" {!! Route::is('administrator.faqs.all')  ? 'is-active' : '' !!} " href="{{ route('administrator.faqs.all')}}">All Faqs</a></li>
    <li><a class=" {{{ (Route::is('administrator.faqs.new') ? 'is-active' : '') }}} " href="{{ route('administrator.faqs.new')}}">New Faq</a></li>
  </ul>
  <p class="menu-label"> Rule & Regulation</p>
  <ul class="menu-list">
     <li><a class=" {!! Route::is('administrator.rules.all')  ? 'is-active' : '' !!} " href="{{ route('administrator.rules.all')}}">All Rules</a></li>
    <li><a class=" {{{ (Route::is('administrator.rules.new') ? 'is-active' : '') }}} " href="{{ route('administrator.rules.new')}}">New Rule</a></li>
  </ul>
  <p class="menu-label"> Setting Manager</p>
  <ul class="menu-list">
     <li><a class=" {!! Route::is('administrator.pages.homepage')  ? 'is-active' : '' !!} " href="{{ route('administrator.pages.homepage')}}">Homepage</a></li>
     <li><a class=" {!! Route::is('administrator.pages.about')  ? 'is-active' : '' !!} " href="{{ route('administrator.pages.about')}}">About</a></li>
     <li><a class=" {!! Route::is('administrator.pages.generalsettings')  ? 'is-active' : '' !!} " href="{{ route('administrator.pages.generalsettings')}}">General Settings</a></li>
  </ul>
</aside>

resources/views/partials/donationsheader.blade.php
<nav class="level is-mobile">
  <div class="level-item has-text-centered">
	<div>
	  <p class="heading">Contributions</p>
	  <p class="title">{{ $funds_made }}</p>
	</div>
  </div>
  <div class="level-item has-text-centered">
	<div>
	  <p class="heading">Donated</p>
	  <p class="title">{{ $total_received }}</p>
	</div>
  </div>
  <div class="level-item has-text-centered">
	<div>
	  <p class="heading">Withdrawals</p>
	  <p class="title">0</p>
	</div>
  </div>
  <div class="level-item has-text-centered">
	<div>
	  <p class="heading">Balance</p>
	  <p class="title">0</p>
	</div>
  </div>
</nav>

resources/views/partials/eventsingledefault.blade.php
<article class="columns">
  <div class="column is-5">
	<figure class="image is-3by2">
		@forelse ($event -> images as $image)
		   @if ($loop->first)
			<img src="{{ asset('storage/'.$image->name) }}" alt="">
		   @endif
		@empty
		@endforelse
	</figure>
  </div>
  <div class="column">
	 <h5 class="title m-b-0-5">{{ $event-> title }}</h5>
     <p class=" m-b-0-2">
		<span class="icon is-small"><i class="fa fa-calendar"></i></span>  Venue : {{ $event-> venue }}

	</p>
	@isset( $event->start_date)
	<p class=" m-b-0-5">
		<span class="icon is-small"><i class="fa fa-calendar"></i></span> From : {{ $event->start_date ->toFormattedDateString() }}
	</p>
	 @endisset
	<div class="content">
		{!! Helper::words( strip_tags($event->description), $limit = 20, $end = '...') !!}
	</div>
	<nav class="level is-mobile">
	  <div class="level-left">
		<div class="level-item">
			<p class="field">
				@isset( $event->fee)
					<span class="icon is-small"><i class="fa fa-money"></i></span> Fee:    {{ $event->fee }}
				@endisset
			</p>
		</div>
	  </div>
	  <div class="level-right">
		<div class="level-item">
			<div class="field ">
			  <p class="control">
				<a href="{{ route('events.show', ['id' => $event -> id ]) }}" class="button is-primary">Read More</a>
			  </p>
			</div>
	    </div>
	  </div>
	</nav>
  </div>
</article>

resources/views/partials/postsingledefault.blade.php
<article class="columns">
  <div class="column is-5">
	<figure class="image is-3by2">
		@foreach ($post -> images as $image)
		   @if ($loop->first)
			<img src="{{ asset('storage/'.$image->name) }}" alt="">
		   @endif
		@endforeach
	</figure>
  </div>
  <div class="column">
	 <h5 class="title">{{ $post-> title }}</h5>
     <h6 class="subtitle">By {{ $post->user->f_name }}  <small class="is-pulled-right"><span class="icon is-small"><i class="fa fa-calendar"></i></span> {{ $post->created_at -> diffForHumans() }} </small></h6>
	<div class="content">
		{!! Helper::words( strip_tags($post->description), $limit = 20, $end = '...') !!}
	</div>
	<nav class="level is-mobile">
	  <div class="level-left">
		<div class="level-item">
			<p class="field">
				<small class=" ">
				  <span class="icon "><i class="fa fa-reply"></i></span>
				  <span class="">23 Replys</span>
				</small>
			</p>
		</div>
	  </div>
	  <div class="level-right">
		<div class="level-item">
			<div class="field ">
			  <p class="control">
				<a href="{{ route('blog.show', ['id' => $post -> id ]) }}" class="button is-primary">Read More</a>
			  </p>
			</div>
	    </div>
	  </div>
	</nav>
  </div>
</article>

resources/views/partials/postsinglefooter.blade.php
<article class="media">
  <div class="media-left">
	 @foreach ($post -> images as $image)
	   @if ($loop->first)
	   	<figure class="image is-96x96">
		  <img src="{{ asset('storage/'.$image->name) }}" alt="">
		</figure>
	   @endif
	@endforeach
  </div>
  <div class="media-content">
	<div class="content">
	  <p>
		<strong>{{ $post-> title }}</strong> <small>@ {{ $post-> user -> f_name }}</small> <small style="float:right;">{{ $post-> created_at -> diffForHumans() }}</small>
		<br>
		{!! Helper::words( strip_tags($post->description), $limit = 8, $end = '...') !!}
		<a href="{{ route('blog.show', ['id' => $post -> id ]) }}" class="">Read More</a>
	  </p>
	</div>
  </div>
</article>

resources/views/partials/postsinglegrid.blade.php
<div class="column is-4">
		<div class="card">
		  <div class="card-image">
			<figure class="image is-4by3">
				@foreach ($post -> images as $image)
				   @if ($loop->first)
					<img src="{{ asset('storage/'.$image->name) }}" alt="">
				   @endif
				@endforeach
			</figure>
		  </div>
		  <div class="card-content">
			<div class="media">
			  <div class="media-left">
				@forelse ($post -> user-> images as $image)
					   @if ($loop->first)
						<figure class="image is-48x48">
						  <img src="{{ asset('storage/'.$image->name) }}" alt="">
						</figure>
					   @endif
				 @empty

				 @endforelse
			  </div>
			  <div class="media-content">
				<p class="title is-4">{{ $post-> title }} </p>
				<p class="subtitle is-6">@ {{ $post->user->f_name }} <small class="is-pulled-right">{{ $post->created_at  -> diffForHumans() }}</small></p>
			  </div>
			</div>

			<div class="content">

				<p> {!! Helper::words( strip_tags($post->description), $limit = 20, $end = '...') !!} </p>

			</div>

		 </div>
		  <footer class="card-footer">
			  <a href="{{ route('blog.show', ['id' => $post -> id ]) }}" class="card-footer-item">Read More</a>
		  </footer>
		</div>

</div>

resources/views/partials/projectdashcard.blade.php
<div class="column is-4">
<div class="card">
  <div class="card-image">
				<figure class="image is-4by3">
					@foreach ($project -> images as $image)
					   @if ($image->featured)
						<img src="{{ asset('storage/'.$image->name) }}" alt="">
				       @endif
				    @endforeach

				</figure>
			  </div>
			  <div class="card-content">
				<p class="title is-4"> {{ $project-> title }}</p>
				<p class="subtitle is-6">@ {{ $project-> user -> f_name }}
				   <span class="timestamp">
					 <strong> @if($project->end_date->isPast()) Ended @else {{  $project-> end_date->diffInDays(null, true) }} days Remaining @endif</strong>
					</span>
				</p>

				<div class="">
				  <span class="tag is-dark">#{{ $project-> category -> name }}</span>
				</div>
				<div class="content">
					{!! Helper::words( strip_tags($project->description), $limit = 13, $end = '...') !!}
				</div>
				<progress class="progress is-success" value="{{ ($project->payments->sum('amount')/$project-> amount) * 100 }}" max="100">{{ ($project->payments->sum('amount')/$project-> amount) * 100 }}%</progress>
				<div class="level is-marginless is-mobile">
					<div class="level-left">
					{{--
					  <div class="level-item">
						<div>
						  <p class="">Raised : <strong> {{ $project->payments->sum('amount') }} </strong></p>
						</div>
					  </div>
				    --}}
					 </div>
					 <div class="level-right">
					   <div class="level-item ">
						 <div>
							 <p class="">Goal : <strong>{{ $project-> amount }}</strong></p>
						</div>
						</div>
					 </div>
				</div>

			  </div>
			  <footer class="card-footer">
	<a href="{{ route('myproject', ['id' => $project-> id])  }}" class="card-footer-item">View</a>
  </footer>
</div>
</div>

resources/views/partials/projectheader.blade.php
<nav class="level is-mobile">
  <div class="level-item has-text-centered">
	<div>
	  <p class="heading">Target</p>
	  <p class="title">{{ $project-> amount }}</p>
	</div>
  </div>
   {{--
  <div class="level-item has-text-centered">
	<div>
	  <p class="heading">Raised</p>
	  <p class="title">{{ $project->payments->sum('amount') }}</p>
	</div>
  </div>
   --}}
  <div class="level-item has-text-centered">
	<div>
	  <p class="heading">Duration</p>
	  <p class="title">{{  $project-> end_date->diffInDays($project-> start_date, true) }}</p>
	</div>
  </div>
  <div class="level-item has-text-centered">
	<div>
	  <p class="heading">Days Remaining</p>
	  <p class="title"> @if($project->end_date->isPast()) ENDED  @else {{  $project-> end_date->diffInDays(null, true) }}  @endif</p>
	</div>
  </div>
</nav>

resources/views/partials/singletestimony.blade.php
<article class="media">
  <figure class="media-left">
	<p class="image is-96x96">
		<img src="{{ asset('storage/'.$post->image->name) }}" alt="">
	</p>
  </figure>
  <div class="media-content">
	<div class="content">
	  <p>
		<strong>{{ $post->name }}</strong> <small>@ {{ $post->alias }}</small>
	  </p>
	  {!! Helper::words( strip_tags($post->content), $limit = 8, $end = '...') !!}
	</div>
  </div>
</article>

resources/views/partials/singleuserheader.blade.php
<ul>
  <li class="{{ $partials_profile_active }} "><a href="{{ route('administrator.users.profile', ['id' => $user-> id]) }}" ><span class="icon"><i class="fa fa-th"></i></span> <span>Profile</span></a></li>
  <li class="{{ $partials_project_active }} " ><a href="{{ route('administrator.users.single', ['id' => $user-> id]) }}" ><span class="icon"><i class="fa fa-list"></i></span> <span>Projects</span></a></li>
  <li class="{{ $partials_trans_active }} "><a href="{{ route('administrator.users.transactions', ['id' => $user-> id]) }}" ><span class="icon"><i class="fa fa-heart"></i></span> <span>Transactions</span></a></li>
  <li class="{{ $partials_membership_active }} "><a href="{{ route('administrator.users.membership', ['id' => $user-> id]) }}" ><span class="icon"><i class="fa fa-user-o"></i></span> <span>Membership</span></a></li>
  <li class="{{ $partials_commisions_active }} "><a href="{{ route('administrator.users.commisions', ['id' => $user-> id]) }}" ><span class="icon"><i class="fa fa-money"></i></span> <span>Commisions</span></a></li>
  <li class="{{ $partials_banking_active }} "><a href="{{ route('administrator.users.banking', ['id' => $user-> id]) }}" ><span class="icon"><i class="fa fa-bank"></i></span> <span>Banking</span></a></li>
</ul>

resources/views/partials/table-chart-header.blade.php
<div class="columns is-gapless is-paddingless is-marginless">
	<div class="column">
		<div class="profile-options p-t-1">
		  <div class="tabs is-fullwidth">
			  <ul class="b-bt">
				  <li class="{!! $t_active !!} link"><a href="{{ route($t_route)}}"> <span class="icon"><i class="fa fa-list"></i></span> <span> Table </span></a></li>
				  <li class="{!! $c_active !!} link"  ><a href="{{ route($c_route) }}" ><span class="icon"><i class="fa fa-th"></i></span> <span>Chart</span></a></li>
			  </ul>
		  </div>
		</div>
	</div>
</div>