routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PagesController@index')->name('home');
Route::get('/about', 'PagesController@about')->name('about');
Route::get('/donations', 'PagesController@donations')->name('donations');
Route::get('/join', 'PagesController@join')->name('join')->middleware('guest');

Route::get('/contacts', function () {
    return view('contacts');
})->name('contacts');

Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/suspended', 'UserController@suspended');
Route::get('emailverification/{token}', 'UserController@emailverify')->name('emailverify.index')->middleware('guest');
Route::post('emailverification/{token}', 'UserController@emailverifyupdate')->name('emailverify.store')->middleware('guest');
Route::get('membershippayment/{memberid}', 'UserController@membershipPayment')->name('membershippayment');

Auth::routes();

Route::group(['prefix' => 'administrator', 'middleware' => ['auth', 'checkadmin' ], 'as'=>'administrator.'], function () {
	Route::get('/', 'AdminController@index')->name('dashboard');
	Route::group(['prefix' => 'users', 'as'=>'users.'], function () {
		Route::get('single/{id}/projects', 'AdminController@singleUser')->name('single');
		Route::get('single/{id}/trasactions', 'AdminController@singleUsertrasactions')->name('transactions');
		Route::get('single/{id}/profile', 'AdminController@singleUserprofile')->name('profile');
		Route::get('single/{id}/membership', 'AdminController@singleUsermembership')->name('membership');
		Route::get('single/{id}/commisions', 'AdminController@singleUsercommisions')->name('commisions');
		Route::get('single/{id}/banking', 'AdminController@singleUserbanking')->name('banking');
		Route::get('table', 'AdminController@alluserstable')->name('table');
		Route::get('chart', 'AdminController@alluserschart')->name('chart');
	});
	Route::group(['prefix' => 'permisions', 'as'=>'permisions.'], function () {
		Route::get('single/{id}', 'AdminController@singlePermision')->name('single');
		Route::get('table', 'AdminController@allpermisions')->name('all');
		Route::post('addroleuser', 'AdminController@addUserRole')->name('adduserrole');
		Route::post('removeroleuser/{userid}/{roleid}', 'AdminController@removeRoleUser')->name('removeroleuser');
	});

	Route::group(['prefix' => 'projects', 'as'=>'projects.'], function () {
		Route::get('single/{id}', 'AdminController@singleProject')->name('single');
		Route::get('table', 'AdminController@allprojects')->name('all');
		Route::get('chart', 'AdminController@allprojectschart')->name('chart');
		Route::get('single/{id}/donations', 'AdminController@viewprojectdonations')->name('projectdonations');
		Route::get('single/{id}/messages', 'AdminController@viewprojectmessages')->name('projectmessages');
		Route::get('single/{id}/settings', 'AdminController@viewprojectsettings')->name('projectsettings');
		Route::get('single/{id}/stats', 'AdminController@viewprojectstats')->name('projectstats');
	});

	Route::group(['prefix' => 'events', 'as'=>'events.'], function () {
		Route::get('single/{id}/view', 'AdminController@singleEvent')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singleEventEdit')->name('edit');
		Route::get('table', 'AdminController@alleventstable')->name('all');
		Route::get('chart', 'AdminController@alleventschart')->name('chart');
		Route::get('new', 'AdminController@newevent')->name('new');
	});

	Route::group(['prefix' => 'blog', 'as'=>'blog.'], function () {
		Route::get('single/{id}/view', 'AdminController@singlePost')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singlePostEdit')->name('edit');
		Route::get('table', 'AdminController@allblogposts')->name('all');
		Route::get('chart', 'AdminController@allblogpostschart')->name('chart');
		Route::get('new', 'AdminController@newblogpost')->name('new');
	});

	Route::group(['prefix' => 'payments', 'as'=>'payments.'], function () {
		Route::get('all', 'AdminController@allPaymentsreceived')->name('allreceived');
		Route::get('single/{id}', 'AdminController@singlePaymentreceivedTrans')->name('single');
	});

	Route::group(['prefix' => 'faqs', 'as'=>'faqs.'], function () {
		Route::get('all', 'AdminController@allFaqs')->name('all');
		Route::get('single/{id}/view', 'AdminController@singleFaq')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singleFaqEdit')->name('edit');
		Route::get('new', 'AdminController@createFaq')->name('new');
	});

	Route::group(['prefix' => 'rules', 'as'=>'rules.'], function () {
		Route::get('all', 'AdminController@allRules')->name('all');
		Route::get('single/{id}/view', 'AdminController@singleRules')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singleRulesEdit')->name('edit');
		Route::get('new', 'AdminController@createRules')->name('new');
	});

	Route::group(['prefix' => 'pages', 'as'=>'pages.'], function () {
		Route::get('homepage', 'AdminController@homepageSetings')->name('homepage');
		Route::get('about', 'AdminController@aboutSetings')->name('about');
		Route::get('generalsettings', 'AdminController@generalSettings')->name('generalsettings');
	});

});

Route::group(['prefix' => 'datatables', 'middleware' => ['auth', 'checkadmin' ], 'as'=>'datatables.'], function () {
	Route::any('newusers', 'DatatableController@newusers')->name('newusers');
	Route::any('allusers', 'DatatableController@allusers')->name('allusers');
	Route::any('allpermisions', 'DatatableController@allpermisions')->name('allpermisions');
	Route::any('singlepermision/{id}', 'DatatableController@singlePermision')->name('singlepermision');
	Route::any('allprojects', 'DatatableController@allprojects')->name('allprojects');
	Route::any('allevents', 'DatatableController@allevents')->name('allevents');
	Route::any('allposts', 'DatatableController@allposts')->name('allposts');
	Route::any('allpaymentsreceived', 'DatatableController@allpaymentsreceived')->name('allpaymentsreceived');
	Route::any('allfaqs', 'DatatableController@allfaqs')->name('allfaqs');
	Route::any('allrules', 'DatatableController@allrules')->name('allrules');
	Route::any('testmonials', 'DatatableController@testmonials')->name('testmonials');
	Route::any('slider', 'DatatableController@settingSlider')->name('settingslider');
	Route::any('sponsors', 'DatatableController@settingSponsors')->name('sponsors');
	Route::any('founders', 'DatatableController@founders')->name('founders');
	Route::post('deleteslider', 'DatatableController@deleteSlider')->name('deleteslider');
	Route::post('deletesponsor', 'DatatableController@deleteSponsor')->name('deletesponsor');
	Route::post('deletetestmonial', 'DatatableController@deleteTestmonial')->name('deletetestmonial');
	Route::post('deletefounder', 'DatatableController@deleteFounder')->name('deletefounder');
});

Route::group(['prefix' => 'chartdata', 'middleware' => ['auth', 'checkadmin' ], 'as'=>'chartdata.'], function () {
	Route::any('usersvsmonth', 'ChartController@usersVsMonth')->name('usersvsmonth');
	Route::any('projectsvsmonth', 'ChartController@projectsVsmonth')->name('projectsvsmonth');
	Route::any('eventsvsmonth', 'ChartController@eventsVsmonth')->name('eventsvsmonth');
	Route::any('postsvsmonth', 'ChartController@postsVsmonth')->name('postsvsmonth');
});

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::get('createproject', 'HomeController@createproject')->name('createproject');
    Route::get('myproject/{id}/view', 'HomeController@viewproject')->name('myproject');
    Route::get('myproject/{id}/donations', 'HomeController@viewprojectdonations')->name('myprojectdonations');
    Route::get('myproject/{id}/messages', 'HomeController@viewprojectmessages')->name('myprojectmessages');
    Route::get('myproject/{id}/messages/{comment}', 'HomeController@viewprojectmessagescomments')->name('viewprojectmessagescomments');
    Route::get('myproject/{id}/settings', 'HomeController@viewprojectsettings')->name('myprojectsettings');
    Route::get('myproject/{id}/stats', 'HomeController@viewprojectstats')->name('myprojectstats');
    Route::get('myprojects', 'HomeController@viewprojects')->name('myprojects');
    Route::get('mycontributions', 'HomeController@mycontributions')->name('mycontributions');
    Route::get('mydonations', 'HomeController@mydonations')->name('mydonations');
    Route::get('mymessages', 'HomeController@mymessages')->name('mymessages');
    Route::group(['prefix' => 'profile', 'as'=>'profile.'], function () {
		Route::get('/', 'HomeController@myProfile')->name('index');
	});

	Route::group(['as'=>'dash.'], function () {
		Route::get('transactions', 'HomeController@myTransactions')->name('transactions');
		Route::get('membership', 'HomeController@myMembership')->name('membership');
		Route::get('commisions', 'HomeController@myCommisions')->name('commisions');
		Route::get('banking', 'HomeController@myBanking')->name('banking');
	});

	Route::group(['prefix' => 'chartdata', 'as'=>'analytics.'], function () {
		Route::any('donationsvsmonth/{id}', 'ChartController@donationsVsmonth')->name('donations');
	});

});

Route::get('projects/{id}/messages', 'ProjectController@projectmessages')->name('projectmessages');
// Route::get('projects/{id}/donations', 'ProjectController@projectdonations')->name('projectdonations');
Route::any('mailboxes/{id}/sent', 'MailboxController@sentmail')->name('mailboxes.sentmail');
Route::any('mailboxes/{id}/inbox', 'MailboxController@inboxmail')->name('mailboxes.inboxmail');

Route::resource('photos', 'ImageController');

resources/views/partials/admin/eventheader.blade.php
<nav class="level is-mobile">
  <div class="level-item has-text-centered">
	<div>
	  <p class="title">Posted On</p>
	  <p class="sub-title">{{ $event->created_at->format('Y/m/d') }}</p>
	</div>
  </div>
  <div class="level-item has-text-centered">
	<div>
	  <p class="title">Posted By</p>
	  <p class="sub-title">{{ $event-> user -> f_name }} {{ $event-> user -> l_name  }}</p>
	</div>
  </div>
  <div class="level-item has-text-centered">
	<div>
	  <p class="title">Views</p>
	  <p class="sub-title">0</p>
	</div>
  </div>
  <div class="level-item ">
		<div class="block has-text-right">
		  <a href="{{ route('administrator.events.edit', ['id' => $event-> id ]) }}" class="button is-warning is-medium">Edit</a>
		  <button id="event_delete_button-btn-control" class="button is-danger is-medium">Delete</button>
		</div>
  </div>
</nav>

resources/views/partials/admin/eventheading.blade.php
<p class="title is-3"><strong>{{ $event-> title }}</strong></p>
<p class="subtitle is-4 is-dark">{{ $event-> tag_line }}</p>
<p class="subtitle is-5"><strong>Venue : {{ $event-> venue }} </strong></p>
<p class="subtitle is-5">
	@isset( $event->start_date) <span class="icon is-small"><i class="fa fa-calendar"></i></span> From : {{ $event->start_date ->toFormattedDateString() }}  @endisset
	@isset( $event->end_date) |  <span class="icon is-small"><i class="fa fa-calendar"></i></span> To:    {{ $event->end_date ->toFormattedDateString() }} @endisset
</p>
@isset( $event->fee)
<p class="subtitle is-5">
	<span class="icon is-small"><i class="fa fa-calendar"></i></span> Fee:    {{ $event->fee }}
</p>
@endisset

resources/views/partials/admin/faqssheader.blade.php
<nav class="level is-mobile">
  <div class="level-item has-text-centered">
	<div>
	  <p class="title">Posted On</p>
	  <p class="sub-title">{{ $faq->created_at->format('Y/m/d') }}</p>
	</div>
  </div>
  <div class="level-item has-text-centered">
	<div>
	  <p class="title">Posted By</p>
	  <p class="sub-title">{{ $faq-> user -> f_name }} {{ $faq-> user -> l_name  }}</p>
	</div>
  </div>
  <div class="level-item has-text-centered">
	<div>
	  <p class="title">Views</p>
	  <p class="sub-title">0</p>
	</div>
  </div>
  <div class="level-item ">
		<div class="block has-text-right">
		  <a href="{{ route('administrator.faqs.edit', ['id' => $faq-> id ]) }}" class="button is-warning is-medium">Edit</a>
		  <button id="faqs_delete_button-btn-control" class="button is-danger is-medium">Delete</button>
		</div>
  </div>
</nav>

resources/views/partials/admin/postsheader.blade.php
<nav class="level is-mobile">
  <div class="level-item has-text-centered">
	<div>
	  <p class="title">Posted On</p>
	  <p class="sub-title">{{ $post->created_at->format('Y/m/d') }}</p>
	</div>
  </div>
  <div class="level-item has-text-centered">
	<div>
	  <p class="title">Posted By</p>
	  <p class="sub-title">{{ $post-> user -> f_name }} {{ $post-> user -> l_name  }}</p>
	</div>
  </div>
  <div class="level-item has-text-centered">
	<div>
	  <p class="title">Views</p>
	  <p class="sub-title">0</p>
	</div>
  </div>
  <div class="level-item ">
		<div class="block has-text-right">
		  <a href="{{ route('administrator.blog.edit', ['id' => $post-> id ]) }}" class="button is-warning is-medium">Edit</a>
		  <button id="post_delete_button-btn-control" class="button is-danger is-medium">Delete</button>
		</div>
  </div>
</nav>

resources/views/partials/admin/projectcard.blade.php
<div class="card">
  <div class="card-image">
				<figure class="image is-4by3">
					@foreach ($project -> images as $image)
					   @if ($image->featured)
						<img src="{{ asset('storage/'.$image->name) }}" alt="">
				       @endif
				    @endforeach

				</figure>
			  </div>
			  <div class="card-content">
				<p class="title is-4"> {{ $project-> title }}</p>
				<p class="subtitle is-6">@ {{ $project-> user -> f_name }}
				   <span class="timestamp">
					 <strong> @if($project->end_date->isPast()) Ended @else {{  $project-> end_date->diffInDays(null, true) }} days Remaining @endif</strong>
					</span>
				</p>

				<div class="">
				  <span class="tag is-dark">#{{ $project-> category -> name }}</span>
				</div>
				<div class="content">
					{!! Helper::words( strip_tags($project->description), $limit = 13, $end = '...') !!}
				</div>
				<progress class="progress is-success" value="{{ ($project->payments->sum('amount')/$project-> amount) * 100 }}" max="100">{{ ($project->payments->sum('amount')/$project-> amount) * 100 }}%</progress>
				<div class="level is-marginless is-mobile">
					<div class="level-left">
						{{--
					  <div class="level-item">
						<div>
						  <p class="">Raised : <strong> {{ $project->payments->sum('amount') }} </strong></p>
						</div>
					  </div>
					  --}}
					 </div>
					 <div class="level-right">
					   <div class="level-item ">
						 <div>
							 <p class="">Goal : <strong>{{ $project-> amount }}</strong></p>
						</div>
						</div>
					 </div>
				</div>

			  </div>
			  <footer class="card-footer">
	<a href="{{ route('administrator.projects.single', ['id' => $project -> id ]) }}" class="card-footer-item">View</a>
  </footer>
</div>

resources/views/partials/admin/projectfooter.blade.php
@push('header-css')
<link rel="stylesheet"  href="//cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.5/sweetalert2.min.css" >
@endpush
@push('scripts')
<script src="//cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.5/sweetalert2.min.js"></script>
<script type="text/javascript">
 $(document).ready(function() {
	  $('#project_deactivate_button-btn-control').click(function(e){
			e.preventDefault();
			var dBtn = $(this);
			swal({
				  title: 'Are you sure?',
				  text: "The User wont access this Project!",
				  type: 'warning',
				  showCancelButton: true,
				  confirmButtonColor: '#3085d6',
				  cancelButtonColor: '#d33',
				  confirmButtonText: 'Yes, De-activate it!'
				}).then(function () {
					$.ajax({
					  headers: {
						'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
					  },
					  method: 'PUT',
					  url: "{{ route('projects.update', ['id' => $partials_project_id])}}",
					  dataType: 'JSON',
					  data: {action: 'deactivate'},
					}).done(function(d) {
						console.log(d);
						if (d.success){
							//~ dBtn.parent('div.block').remove();
							dBtn.prop("disabled", true);
							swal(
							'Deactivated!!',
							'Project deactivated.',
							'success'
						  )
						}

					  });

				}, function (dismiss) {
				  // dismiss can be 'cancel', 'overlay',
				  // 'close', and 'timer'
				  if (dismiss === 'cancel') {
					swal(
					  'Cancelled',
					  'Operation Cancelled',
					  'error'
					)
				  }
				})
	  });
      $('#project_activate_button-btn-control').click(function(e){
			e.preventDefault();
			var dBtn = $(this);
			swal({
				  title: 'Are you sure?',
				  text: "The User will regain access this Project!",
				  type: 'warning',
				  showCancelButton: true,
				  confirmButtonColor: '#3085d6',
				  cancelButtonColor: '#d33',
				  confirmButtonText: 'Yes, Activate it!'
				}).then(function () {
					$.ajax({
					  headers: {
						'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
					  },
					  method: 'PUT',
					  url: "{{ route('projects.update', ['id' => $partials_project_id])}}",
					  dataType: 'JSON',
					  data: {action: 'activate'},
					}).done(function(d) {
						console.log(d);
						if (d.success){
							//~ dBtn.parent('div.block').remove();
							dBtn.prop("disabled", true);
							swal(
							'Activated!!',
							'Project has being Activated.',
							'success'
						  )
						}

					  });

				}, function (dismiss) {
				  // dismiss can be 'cancel', 'overlay',
				  // 'close', and 'timer'
				  if (dismiss === 'cancel') {
					swal(
					  'Cancelled',
					  'Operation Cancelled',
					  'error'
					)
				  }
				})
	  });
      $('#project_delete_button-btn-control').click(function(e){
			e.preventDefault();
			var dBtn = $(this);
			swal({
				  title: 'Are you sure?',
				  text: "You won't be able to revert this!",
				  type: 'warning',
				  showCancelButton: true,
				  confirmButtonColor: '#3085d6',
				  cancelButtonColor: '#d33',
				  confirmButtonText: 'Yes, delete it!'
				}).then(function () {
					$.ajax({
					  headers: {
						'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
					  },
					  method: 'DELETE',
					  url: "{{ route('projects.destroy', ['id' => $partials_project_id])}}",
					  dataType: 'JSON',
					}).done(function(d) {
						console.log(d);
						if (d.success){
							dBtn.parent('div.block').remove();
							swal(
							'Deleted!',
							'Projects deleted.',
							'success'
						  )
						}

					  });

				}, function (dismiss) {
				  // dismiss can be 'cancel', 'overlay',
				  // 'close', and 'timer'
				  if (dismiss === 'cancel') {
					swal(
					  'Cancelled',
					  'Operation Cancelled',
					  'error'
					)
				  }
				})
	  });

  });
</script>
@endpush

resources/views/partials/admin/projectheading.blade.php
<div class="columns">
	  <div class="column">
				<p class="title m-b-0-5">{{ $project-> title }}</p>
				<p class=""><a class="">{{ $project-> user -> f_name }} {{ $project-> user -> l_name  }}</a></p>
	  </div>
	  <div class="column">
		   <div class="block has-text-right">
			 @if($project->status)
			  <button id="project_deactivate_button-btn-control" class="button is-warning is-medium">Deactivate</button>
			 @else
			  <button id="project_activate_button-btn-control" class="button is-primary is-medium">Activate</button>
			 @endif
			  <button id="project_delete_button-btn-control" class="button is-danger is-medium">Delete</button>
			</div>
	  </div>
</div>

resources/views/partials/admin/projectsubmenu.blade.php
<div class="tabs  is-fullwidth is-boxed">
		<ul>
			<li class="{!! $partials_general_active !!} ">
			  <a href="{{ route('administrator.projects.single', ['id' => $project-> id]) }}">
				<span class="icon is-small"><i class="fa fa-image"></i></span>
				<span>General Details</span>
			  </a>
			</li>
			{{--
			<li class="{!! $partials_donations_active !!} ">
			  <a href="{{ route('administrator.projects.projectdonations', ['id' => $project-> id]) }}">
				<span class="icon is-small"><i class="fa fa-money"></i></span>
				<span>Donations</span>
			  </a>
			</li>
			--}}
			<li class="{!! $partials_messages_active !!} ">
			  <a href="{{ route('administrator.projects.projectmessages', ['id' => $project-> id]) }}" >
				<span class="icon is-small"><i class="fa fa-comments-o"></i></span>
				<span>Messages</span>
			  </a>
			</li>
			{{--
			<li class="{!! $partials_stats_active !!} ">
			  <a href="{{ route('administrator.projects.projectstats', ['id' => $project-> id]) }}" >
				<span class="icon is-small"><i class="fa fa-chart-line-o"></i></span>
				<span>Stats</span>
			  </a>
			</li>
			--}}
		</ul>

</div>

resources/views/partials/admin/rulessheader.blade.php
<nav class="level is-mobile">
  <div class="level-item has-text-centered">
	<div>
	  <p class="title">Posted On</p>
	  <p class="sub-title">{{ $rule->created_at->format('Y/m/d') }}</p>
	</div>
  </div>

  <div class="level-item has-text-centered">
	<div>
	  <p class="title">Views</p>
	  <p class="sub-title">0</p>
	</div>
  </div>
  <div class="level-item ">
		<div class="block has-text-right">
		  <a href="{{ route('administrator.rules.edit', ['id' => $rule-> id ]) }}" class="button is-warning is-medium">Edit</a>
		  <button id="rule_delete_button-btn-control" class="button is-danger is-medium">Delete</button>
		</div>
  </div>
</nav>

resources/views/partials/admin/userlevels.blade.php
<p class="title is-4 m-b-0-5 is-spaced"> {{ $user -> f_name }} {{ $user -> l_name }} </p>
<p class="subtitle is-6 m-b-0-5">@ {{ $user -> email }} </p>
<p class="subtitle is-bold is-6 m-b-0-5">{{ $user -> member_id }} </p>
@if ($user->is_pending)
	 <span class="tag is-warning is-small">PENDING VERIFICATION </span>
@else
   @if ($user->status && $user->is_paid)
	 <span class="tag is-primary is-small">ACTIVE</span>
   @elseif ($user->is_paid && !$user->status)
	 <span class="tag is-warning is-small">SUSPENDED</span>
   @elseif (!$user->is_paid)
	 <span class="tag is-warning is-small">NOT PAID</span>
   @else
	 <span class="tag is-danger is-small">NEEDS REVIEW</span>
   @endif
@endif
<nav class="level is-mobile">

  <div class="level-item has-text-centered">
	<div>
	  <p class="heading">Projects</p>
	  <p class="title">{{ $user -> projects -> count() }}</p>
	</div>
  </div>
  <div class="level-item has-text-centered">
	<div>
	  <p class="heading">Transactions</p>
	  <p class="title">{{ $payments_count}}</p>
	</div>
  </div>
  {{--
  <div class="level-item has-text-centered">
	<div>
	  <p class="heading">Withdrawals</p>
	  <p class="title">0</p>
	</div>
  </div>
  <div class="level-item has-text-centered">
	<div>
	  <p class="heading">Balance</p>
	  <p class="title">0</p>
	</div>
  </div>
  --}}
</nav>