routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PagesController@index')->name('home');
Route::get('/about', 'PagesController@about')->name('about');
Route::get('/donations', 'PagesController@donations')->name('donations');
Route::get('/join', 'PagesController@join')->name('join')->middleware('guest');

Route::get('/contacts', function () {
    return view('contacts');
})->name('contacts');

Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/suspended', 'UserController@suspended');
Route::get('emailverification/{token}', 'UserController@emailverify')->name('emailverify.index')->middleware('guest');
Route::post('emailverification/{token}', 'UserController@emailverifyupdate')->name('emailverify.store')->middleware('guest');
Route::get('membershippayment/{memberid}', 'UserController@membershipPayment')->name('membershippayment');

Auth::routes();

Route::group(['prefix' => 'administrator', 'middleware' => ['auth', 'checkadmin' ], 'as'=>'administrator.'], function () {
	Route::get('/', 'AdminController@index')->name('dashboard');
	Route::group(['prefix' => 'users', 'as'=>'users.'], function () {
		Route::get('single/{id}/projects', 'AdminController@singleUser')->name('single');
		Route::get('single/{id}/trasactions', 'AdminController@singleUsertrasactions')->name('transactions');
		Route::get('single/{id}/profile', 'AdminController@singleUserprofile')->name('profile');
		Route::get('single/{id}/membership', 'AdminController@singleUsermembership')->name('membership');
		Route::get('single/{id}/commisions', 'AdminController@singleUsercommisions')->name('commisions');
		Route::get('single/{id}/banking', 'AdminController@singleUserbanking')->name('banking');
		Route::get('table', 'AdminController@alluserstable')->name('table');
		Route::get('chart', 'AdminController@alluserschart')->name('chart');
	});
	Route::group(['prefix' => 'permisions', 'as'=>'permisions.'], function () {
		Route::get('single/{id}', 'AdminController@singlePermision')->name('single');
		Route::get('table', 'AdminController@allpermisions')->name('all');
		Route::post('addroleuser', 'AdminController@addUserRole')->name('adduserrole');
		Route::post('removeroleuser/{userid}/{roleid}', 'AdminController@removeRoleUser')->name('removeroleuser');
	});

	Route::group(['prefix' => 'projects', 'as'=>'projects.'], function () {
		Route::get('single/{id}', 'AdminController@singleProject')->name('single');
		Route::get('table', 'AdminController@allprojects')->name('all');
		Route::get('chart', 'AdminController@allprojectschart')->name('chart');
		Route::get('single/{id}/donations', 'AdminController@viewprojectdonations')->name('projectdonations');
		Route::get('single/{id}/messages', 'AdminController@viewprojectmessages')->name('projectmessages');
		Route::get('single/{id}/settings', 'AdminController@viewprojectsettings')->name('projectsettings');
		Route::get('single/{id}/stats', 'AdminController@viewprojectstats')->name('projectstats');
	});

	Route::group(['prefix' => 'events', 'as'=>'events.'], function () {
		Route::get('single/{id}/view', 'AdminController@singleEvent')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singleEventEdit')->name('edit');
		Route::get('table', 'AdminController@alleventstable')->name('all');
		Route::get('chart', 'AdminController@alleventschart')->name('chart');
		Route::get('new', 'AdminController@newevent')->name('new');
	});

	Route::group(['prefix' => 'blog', 'as'=>'blog.'], function () {
		Route::get('single/{id}/view', 'AdminController@singlePost')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singlePostEdit')->name('edit');
		Route::get('table', 'AdminController@allblogposts')->name('all');
		Route::get('chart', 'AdminController@allblogpostschart')->name('chart');
		Route::get('new', 'AdminController@newblogpost')->name('new');
	});

	Route::group(['prefix' => 'payments', 'as'=>'payments.'], function () {
		Route::get('all', 'AdminController@allPaymentsreceived')->name('allreceived');
		Route::get('single/{id}', 'AdminController@singlePaymentreceivedTrans')->name('single');
	});

	Route::group(['prefix' => 'faqs', 'as'=>'faqs.'], function () {
		Route::get('all', 'AdminController@allFaqs')->name('all');
		Route::get('single/{id}/view', 'AdminController@singleFaq')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singleFaqEdit')->name('edit');
		Route::get('new', 'AdminController@createFaq')->name('new');
	});

	Route::group(['prefix' => 'rules', 'as'=>'rules.'], function () {
		Route::get('all', 'AdminController@allRules')->name('all');
		Route::get('single/{id}/view', 'AdminController@singleRules')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singleRulesEdit')->name('edit');
		Route::get('new', 'AdminController@createRules')->name('new');
	});

	Route::group(['prefix' => 'pages', 'as'=>'pages.'], function () {
		Route::get('homepage', 'AdminController@homepageSetings')->name('homepage');
		Route::get('about', 'AdminController@aboutSetings')->name('about');
		Route::get('generalsettings', 'AdminController@generalSettings')->name('generalsettings');
	});

});

Route::group(['prefix' => 'datatables', 'middleware' => ['auth', 'checkadmin' ], 'as'=>'datatables.'], function () {
	Route::any('newusers', 'DatatableController@newusers')->name('newusers');
	Route::any('allusers', 'DatatableController@allusers')->name('allusers');
	Route::any('allpermisions', 'DatatableController@allpermisions')->name('allpermisions');
	Route::any('singlepermision/{id}', 'DatatableController@singlePermision')->name('singlepermision');
	Route::any('allprojects', 'DatatableController@allprojects')->name('allprojects');
	Route::any('allevents', 'DatatableController@allevents')->name('allevents');
	Route::any('allposts', 'DatatableController@allposts')->name('allposts');
	Route::any('allpaymentsreceived', 'DatatableController@allpaymentsreceived')->name('allpaymentsreceived');
	Route::any('allfaqs', 'DatatableController@allfaqs')->name('allfaqs');
	Route::any('allrules', 'DatatableController@allrules')->name('allrules');
	Route::any('testmonials', 'DatatableController@testmonials')->name('testmonials');
	Route::any('slider', 'DatatableController@settingSlider')->name('settingslider');
	Route::any('sponsors', 'DatatableController@settingSponsors')->name('sponsors');
	Route::any('founders', 'DatatableController@founders')->name('founders');
	Route::post('deleteslider', 'DatatableController@deleteSlider')->name('deleteslider');
	Route::post('deletesponsor', 'DatatableController@deleteSponsor')->name('deletesponsor');
	Route::post('deletetestmonial', 'DatatableController@deleteTestmonial')->name('deletetestmonial');
	Route::post('deletefounder', 'DatatableController@deleteFounder')->name('deletefounder');
});

Route::group(['prefix' => 'chartdata', 'middleware' => ['auth', 'checkadmin' ], 'as'=>'chartdata.'], function () {
	Route::any('usersvsmonth', 'ChartController@usersVsMonth')->name('usersvsmonth');
	Route::any('projectsvsmonth', 'ChartController@projectsVsmonth')->name('projectsvsmonth');
	Route::any('eventsvsmonth', 'ChartController@eventsVsmonth')->name('eventsvsmonth');
	Route::any('postsvsmonth', 'ChartController@postsVsmonth')->name('postsvsmonth');
});

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::get('createproject', 'HomeController@createproject')->name('createproject');
    Route::get('myproject/{id}/view', 'HomeController@viewproject')->name('myproject');
    Route::get('myproject/{id}/donations', 'HomeController@viewprojectdonations')->name('myprojectdonations');
    Route::get('myproject/{id}/messages', 'HomeController@viewprojectmessages')->name('myprojectmessages');
    Route::get('myproject/{id}/messages/{comment}', 'HomeController@viewprojectmessagescomments')->name('viewprojectmessagescomments');
    Route::get('myproject/{id}/settings', 'HomeController@viewprojectsettings')->name('myprojectsettings');
    Route::get('myproject/{id}/stats', 'HomeController@viewprojectstats')->name('myprojectstats');
    Route::get('myprojects', 'HomeController@viewprojects')->name('myprojects');
    Route::get('mycontributions', 'HomeController@mycontributions')->name('mycontributions');
    Route::get('mydonations', 'HomeController@mydonations')->name('mydonations');
    Route::get('mymessages', 'HomeController@mymessages')->name('mymessages');
    Route::group(['prefix' => 'profile', 'as'=>'profile.'], function () {
		Route::get('/', 'HomeController@myProfile')->name('index');
	});

	Route::group(['as'=>'dash.'], function () {
		Route::get('transactions', 'HomeController@myTransactions')->name('transactions');
		Route::get('membership', 'HomeController@myMembership')->name('membership');
		Route::get('commisions', 'HomeController@myCommisions')->name('commisions');
		Route::get('banking', 'HomeController@myBanking')->name('banking');
	});

	Route::group(['prefix' => 'chartdata', 'as'=>'analytics.'], function () {
		Route::any('donationsvsmonth/{id}', 'ChartController@donationsVsmonth')->name('donations');
	});

});

Route::get('projects/{id}/messages', 'ProjectController@projectmessages')->name('projectmessages');
// Route::get('projects/{id}/donations', 'ProjectController@projectdonations')->name('projectdonations');
Route::any('mailboxes/{id}/sent', 'MailboxController@sentmail')->name('mailboxes.sentmail');
Route::any('mailboxes/{id}/inbox', 'MailboxController@inboxmail')->name('mailboxes.inboxmail');

Route::resource('photos', 'ImageController');

resources/views/admin/allblogpostschart.blade.php
@extends('layouts.app')

@section('title', 'Dashboard')

@section('content')
<div class="columns is-paddingless is-marginless">
	<div class="column is-narrow">
	    @include('partials.adminmenu')
	</div>
	<div class="column">
			@include('partials.table-chart-header',
					[

					't_active' => '' ,
					'c_active' => 'is-active' ,
					't_route' => 'administrator.blog.all',
					'c_route' => 'administrator.blog.chart'])

			<section class="section p-t-0-5">

					<nav class="level is-mobile">
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">All Posts</p>
						  <p class="title">{{ $all_posts }}</p>
						</div>
					  </div>
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">Active Posts</p>
						  <p class="title">{{ $active_posts }}</p>
						</div>
					  </div>
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">Pending Posts</p>
						  <p class="title">{{ $inactive_posts }}</p>
						</div>
					  </div>
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">Deleted Posts</p>
						  <p class="title">{{ $deleted_posts }}</p>
						</div>
					  </div>
					</nav>

			</section>

			<section class="section p-t-0-5">
				  <div class="columns">
					  <div class="column">
							<p class="title is-5">
							   Posts Vs Months
						   </p>
							<div class="block m-b-0 ">
								<canvas id="posts-chart"></canvas>
							</div>
					  </div>
				  </div>
			</section>

	</div>
</div>
@endsection

@push('scripts')
<script src="{{ asset('js/Chart.js') }}"></script>
<script type="text/javascript">
	var ctxReg = document.getElementById("posts-chart").getContext("2d");
	var postsVsmonth ;
	var chartColors = {
		red: 'rgb(255, 99, 132)',
		orange: 'rgb(255, 159, 64)',
		yellow: 'rgb(255, 205, 86)',
		green: 'rgb(75, 192, 192)',
		blue: 'rgb(54, 162, 235)',
		purple: 'rgb(153, 102, 255)',
		grey: 'rgb(201, 203, 207)'
	};
	var color = Chart.helpers.color;
	var configLine = {
            type: 'line',
            data: {
                labels: [],
                datasets: []
            },
            options: {
                responsive: true,
                title:{
                    display:false,
                },
                tooltips: {
                    mode: 'index',
                    intersect: false,
                },
                hover: {
                    mode: 'nearest',
                    intersect: true
                },
                scales: {
                    xAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Month'
                        }
                    }],
                    yAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Views'
                        }
                    }]
                }
            }
    };

    var configBar = {
		type: 'bar',
		data: {
			labels: [],
			datasets: []
		},
		options: {
				responsive: true,
				legend: {
					position: 'top',
				},
				title: {
					display: false,
				}
		 }
    };

	$(function() {
		$.ajax({
		  headers: {
			'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
		  },
		  method: 'POST',
		  url: "{{ route('chartdata.postsvsmonth')}}",
		  dataType: 'JSON',
		}).done(function(d) {
			console.log(d);
			if (d.success){
				var chLbls = [];
				var chDt = [];
				$.each(d.data, function( key, value ) {
					chLbls.push(key)
					chDt.push(value)
				});
				configBar.data.labels = chLbls ;
				configBar.data.datasets = [{
                    label: "Posts",
                    backgroundColor: color(chartColors.green).alpha(0.5).rgbString(),
                    borderColor: chartColors.green,
                    data: chDt,
                    //~ fill: false,
                    borderWidth: 1,
                }] ;
                postsVsmonth = new Chart(ctxReg, configBar);
			}

		});

	});
</script>
@endpush

resources/views/admin/alleventstable.blade.php
@extends('layouts.app')

@section('title', 'Dashboard')

@section('content')
<div class="columns is-paddingless is-marginless">
	<div class="column is-narrow">
	    @include('partials.adminmenu')
	</div>
	<div class="column">
			@include('partials.table-chart-header',
					[

					't_active' => 'is-active' ,
					'c_active' => '' ,
					't_route' => 'administrator.events.all',
					'c_route' => 'administrator.events.chart'])

			<section class="section p-t-0-5">

					<nav class="level is-mobile">
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">All Events</p>
						  <p class="title">{{ $all_events }}</p>
						</div>
					  </div>
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">Active Events</p>
						  <p class="title">{{ $active_events }}</p>
						</div>
					  </div>
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">Pending Events</p>
						  <p class="title">{{ $inactive_events }}</p>
						</div>
					  </div>
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">Deleted Events</p>
						  <p class="title">{{ $deleted_events }}</p>
						</div>
					  </div>
					</nav>

			</section>

			<section class="section p-t-0-5">
				  <div class="columns">
					  <div class="column">
							<table class="table " id="all_events_dt-table">
								<thead>
									<tr>
										<th></th>
										<th>User</th>
										<th>Title</th>
										<th>Fee</th>
										<th>Venue</th>
										<th>Start date</th>
										<th>End date</th>
										<th></th>
									</tr>
								</thead>
							</table>
					  </div>
				  </div>
			</section>

	</div>
</div>
@endsection

@push('header-css')
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css"/>
@endpush

@push('scripts')
<script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
	$(function() {
		$('#all_events_dt-table').DataTable({
			processing: true,
			serverSide: true,
			lengthChange: false,
			pageLength: 5,
			ajax: "{{ route('datatables.allevents') }}",
			columns: [
				{ data: 'rownum', name: 'rownum', orderable: false, searchable: false},
				{ data: 'user.f_name', name: 'user.f_name'},
				{ data: 'title'},
				{ data: 'fee'},
				{ data: 'venue'},
				{ data: 'start_date'},
				{ data: 'end_date'},
				{data: 'action', name: 'action', orderable: false, searchable: false}
			]
		});
	});
</script>
@endpush

resources/views/admin/allpermisions.blade.php
@extends('layouts.app')

@section('title', 'Dashboard')

@section('content')
<div class="columns is-paddingless is-marginless">
	<div class="column is-narrow">
	    @include('partials.adminmenu')
	</div>
	<div class="column">

			<section class="section p-t-0-5">
				  <div class="columns">
					  <div class="column">
							<table class="table " id="all_roles_dt-table">
								<thead>
									<tr>
										<th></th>
										<th>Name</th>
										<th>User Count</th>
										<th></th>
									</tr>
								</thead>
							</table>
					  </div>
				  </div>
			</section>

	</div>
</div>
@endsection

@push('header-css')
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css"/>
@endpush

@push('scripts')
<script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
	$(function() {
		$('#all_roles_dt-table').DataTable({
			processing: true,
			serverSide: true,
			lengthChange: false,
			pageLength: 5,
			ajax: "{{ route('datatables.allpermisions') }}",
			columns: [
				{ data: 'id', name: 'id', orderable: false, searchable: false},
				{ data: 'slug'},
				{ data: 'counts'},
				{data: 'action', name: 'action', orderable: false, searchable: false}
			]
		});
	});
</script>
@endpush

resources/views/admin/allprojects.blade.php
@extends('layouts.app')

@section('title', 'Dashboard')

@section('content')
<div class="columns is-paddingless is-marginless">
	<div class="column is-narrow">
	    @include('partials.adminmenu')
	</div>
	<div class="column">
			@include('partials.table-chart-header',
					[

					't_active' => 'is-active' ,
					'c_active' => '' ,
					't_route' => 'administrator.projects.all',
					'c_route' => 'administrator.projects.chart'])

			<section class="section p-t-0-5">

					<nav class="level is-mobile">
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">All Projects</p>
						  <p class="title">{{ $all_projects }}</p>
						</div>
					  </div>
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">Active Projects</p>
						  <p class="title">{{ $active_projects }}</p>
						</div>
					  </div>
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">Deactivated Projects</p>
						  <p class="title">{{ $deactivated_projects }}</p>
						</div>
					  </div>
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">Deleted Projects</p>
						  <p class="title">{{ $deleted_projects }}</p>
						</div>
					  </div>
					</nav>

			</section>

			<section class="section p-t-0-5">
				  <div class="columns">
					  <div class="column">
							<table class="table " id="all_projects_dt-table">
								<thead>
									<tr>
										<th></th>
										<th>User</th>
										<th>Title</th>
										<th>Amount Required</th>
										 {{-- <th>Funds Raised</th> --}}
										<th>Start date</th>
										<th>End date</th>
										<th>Days Remain</th>
										<th></th>
									</tr>
								</thead>
							</table>
					  </div>
				  </div>
			</section>

	</div>
</div>
@endsection

@push('header-css')
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css"/>
@endpush

@push('scripts')
<script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
	$(function() {
		$('#all_projects_dt-table').DataTable({
			processing: true,
			serverSide: true,
			lengthChange: false,
			pageLength: 5,
			ajax: "{{ route('datatables.allprojects') }}",
			columns: [
				{ data: 'rownum', name: 'rownum', orderable: false, searchable: false},
				{ data: 'user.f_name', name: 'user.f_name'},
				{ data: 'title'},
				{ data: 'amount'},
				 {{-- { data: 'funds_raised'},  --}}
				{ data: 'start_date'},
				{ data: 'end_date'},
				{ data: 'days_remaining'},
				{data: 'action', name: 'action', orderable: false, searchable: false}
			]
		});
	});
</script>
@endpush

resources/views/admin/alluserstable.blade.php
@extends('layouts.app')

@section('title', 'Dashboard')

@section('content')
<div class="columns is-paddingless is-marginless">
	<div class="column is-narrow">
	    @include('partials.adminmenu')
	</div>
	<div class="column">
			@include('partials.table-chart-header',
					[

					't_active' => 'is-active' ,
					'c_active' => '' ,
					't_route' => 'administrator.users.table',
					'c_route' => 'administrator.users.chart'])

			<section class="section p-t-0-5">

					<nav class="level is-mobile">
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">Admins</p>
						  <p class="title">{{ $admin_users }}</p>
						</div>
					  </div>
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">Active Users</p>
						  <p class="title">{{ $active_users }}</p>
						</div>
					  </div>
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">Pending Users</p>
						  <p class="title">{{ $inactive_users }}</p>
						</div>
					  </div>
					  <div class="level-item has-text-centered">
						<div>
						  <p class="heading">Deleted Users</p>
						  <p class="title">{{ $deleted_users }}</p>
						</div>
					  </div>
					</nav>

			</section>

			<section class="section p-t-0-5">
				  <div class="columns">
					  <div class="column">
							<table class="table " id="all_users_dt-table">
								<thead>
									<tr>
										<th></th>
										<th>Member Id</th>
										<th>First Name</th>
										<th>Last Name</th>
										<th>Email</th>
										<th>Registered On</th>
										<th>Status</th>
										<th></th>
									</tr>
								</thead>
							</table>
					  </div>
				  </div>
			</section>

	</div>
</div>
@endsection

@push('header-css')
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css"/>
@endpush

@push('scripts')
<script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
	$(function() {
		$('#all_users_dt-table').DataTable({
			processing: true,
			serverSide: true,
			lengthChange: false,
			pageLength: 5,
			ajax: "{{ route('datatables.allusers') }}",
			columns: [
				{ data: 'rownum', name: 'rownum', orderable: false, searchable: false},
				{ data: 'member_id'},
				{ data: 'f_name'},
				{ data: 'l_name'},
				{ data: 'email'},
				{ data: 'created_at'},
				{ data: 'status_btn'},
				{data: 'action', name: 'action', orderable: false, searchable: false}
			]
		});
	});
</script>
@endpush

resources/views/admin/singlepermision.blade.php
@extends('layouts.app')

@section('title', 'Dashboard')

@section('content')
<div class="columns is-paddingless is-marginless">
	<div class="column is-narrow">
	    @include('partials.adminmenu')
	</div>
	<div class="column">

			<section class="section p-t-0-5">
				<div class="heading  m-b-3 has-text-centered">
					<h3 class="subtitle">Role : {{ $role->slug }}</h3>
				</div>

				  <div class="columns">
					  <div class="column is-7 b-br">
							<table class="table " id="single_permision_dt-table">
								<thead>
									<tr>
										<th>First Name</th>
										<th>Last Name</th>
										<th>Super Admin</th>
										<th></th>
									</tr>
								</thead>
							</table>
					  </div>
					  <div class="column">
						  <p class="subtitle">Give User Role</p>
						 <div class="field">
							  <label class="label">Role Name </label>
							  <p class="control ">
								<input disabled class="input " type="text" placeholder="{{ $role->slug }}">

							  </p>
						 </div>
						 <div class="field">
							  <label class="label">User </label>
							  <p class="control has-icons-left has-icons-right">
								<span class="select">
								  <select id="form_role-user_id">
									  @foreach ($users as $user)
											<option value="{{ $user -> id }}" >{{ $user -> f_name }} {{ $user -> l_name }}</option>
									  @endforeach
								  </select>
								</span>
								<span class="icon is-small is-left">
								  <i class="fa fa-envelope"></i>
								</span>
							  </p>
						 </div>
						 <div class="field ">
						  <p class="control">
							<button id="add-role_user-btn-control" class="button is-primary">Give Role</button>
						  </p>
						</div>

					  </div>
				  </div>
			</section>

	</div>
</div>
@endsection

@push('header-css')
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css"/>
@endpush

@push('scripts')
<script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
	$(function() {
		var regdata = {};
		 $.ajaxSetup({
			headers: {
				'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
			}
		});

		$('#single_permision_dt-table').DataTable({
			processing: true,
			serverSide: true,
			lengthChange: false,
			pageLength: 5,
			ajax: "{{ route('datatables.singlepermision', ['id' => $role->id ]) }}",
			columns: [
				{ data: 'f_name'},
				{ data: 'l_name'},
				{ data: 'is_admin'},
				{data: 'action', name: 'action', orderable: false, searchable: false}
			]
		});

		$('#add-role_user-btn-control').click(function(e){
			e.preventDefault();
			$(this).prop("disabled", true);
			regdata.role_id = {{ $role->id }};
			regdata.user_id = $("#form_role-user_id").val();
			console.log(regdata);
			addUserRoleForm($(this));
			;
		});
		$('.remove-role_user-btn-control').click(function(e){
			e.preventDefault();
			var lnk = $(this).val();
			console.log(lnk);
			//removeUserRoleForm(lnk);

		});

		function addUserRoleForm(btn) {
			 $.ajax({
			  method: 'POST',
			  url: "{{ route('administrator.permisions.adduserrole')}}",
			  dataType: 'JSON',
			  data: regdata
			}).done(function(d) {
				console.log(d);
				btn.prop("disabled", false)
				if (d.success){

				}

			  });
		 }

		 function removeUserRoleForm(lk) {
			 $.ajax({
			  method: 'POST',
			  url: lk,
			  dataType: 'JSON',
			}).done(function(d) {
				console.log(d);
				if (d.success){

				}

			  });
		 }

	});
</script>
@endpush