routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PagesController@index')->name('home');
Route::get('/about', 'PagesController@about')->name('about');
Route::get('/donations', 'PagesController@donations')->name('donations');
Route::get('/join', 'PagesController@join')->name('join')->middleware('guest');

Route::get('/contacts', function () {
    return view('contacts');
})->name('contacts');

Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/suspended', 'UserController@suspended');
Route::get('emailverification/{token}', 'UserController@emailverify')->name('emailverify.index')->middleware('guest');
Route::post('emailverification/{token}', 'UserController@emailverifyupdate')->name('emailverify.store')->middleware('guest');
Route::get('membershippayment/{memberid}', 'UserController@membershipPayment')->name('membershippayment');

Auth::routes();

Route::group(['prefix' => 'administrator', 'middleware' => ['auth', 'checkadmin' ], 'as'=>'administrator.'], function () {
	Route::get('/', 'AdminController@index')->name('dashboard');
	Route::group(['prefix' => 'users', 'as'=>'users.'], function () {
		Route::get('single/{id}/projects', 'AdminController@singleUser')->name('single');
		Route::get('single/{id}/trasactions', 'AdminController@singleUsertrasactions')->name('transactions');
		Route::get('single/{id}/profile', 'AdminController@singleUserprofile')->name('profile');
		Route::get('single/{id}/membership', 'AdminController@singleUsermembership')->name('membership');
		Route::get('single/{id}/commisions', 'AdminController@singleUsercommisions')->name('commisions');
		Route::get('single/{id}/banking', 'AdminController@singleUserbanking')->name('banking');
		Route::get('table', 'AdminController@alluserstable')->name('table');
		Route::get('chart', 'AdminController@alluserschart')->name('chart');
	});
	Route::group(['prefix' => 'permisions', 'as'=>'permisions.'], function () {
		Route::get('single/{id}', 'AdminController@singlePermision')->name('single');
		Route::get('table', 'AdminController@allpermisions')->name('all');
		Route::post('addroleuser', 'AdminController@addUserRole')->name('adduserrole');
		Route::post('removeroleuser/{userid}/{roleid}', 'AdminController@removeRoleUser')->name('removeroleuser');
	});

	Route::group(['prefix' => 'projects', 'as'=>'projects.'], function () {
		Route::get('single/{id}', 'AdminController@singleProject')->name('single');
		Route::get('table', 'AdminController@allprojects')->name('all');
		Route::get('chart', 'AdminController@allprojectschart')->name('chart');
		Route::get('single/{id}/donations', 'AdminController@viewprojectdonations')->name('projectdonations');
		Route::get('single/{id}/messages', 'AdminController@viewprojectmessages')->name('projectmessages');
		Route::get('single/{id}/settings', 'AdminController@viewprojectsettings')->name('projectsettings');
		Route::get('single/{id}/stats', 'AdminController@viewprojectstats')->name('projectstats');
	});

	Route::group(['prefix' => 'events', 'as'=>'events.'], function () {
		Route::get('single/{id}/view', 'AdminController@singleEvent')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singleEventEdit')->name('edit');
		Route::get('table', 'AdminController@alleventstable')->name('all');
		Route::get('chart', 'AdminController@alleventschart')->name('chart');
		Route::get('new', 'AdminController@newevent')->name('new');
	});

	Route::group(['prefix' => 'blog', 'as'=>'blog.'], function () {
		Route::get('single/{id}/view', 'AdminController@singlePost')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singlePostEdit')->name('edit');
		Route::get('table', 'AdminController@allblogposts')->name('all');
		Route::get('chart', 'AdminController@allblogpostschart')->name('chart');
		Route::get('new', 'AdminController@newblogpost')->name('new');
	});

	Route::group(['prefix' => 'payments', 'as'=>'payments.'], function () {
		Route::get('all', 'AdminController@allPaymentsreceived')->name('allreceived');
		Route::get('single/{id}', 'AdminController@singlePaymentreceivedTrans')->name('single');
	});

	Route::group(['prefix' => 'faqs', 'as'=>'faqs.'], function () {
		Route::get('all', 'AdminController@allFaqs')->name('all');
		Route::get('single/{id}/view', 'AdminController@singleFaq')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singleFaqEdit')->name('edit');
		Route::get('new', 'AdminController@createFaq')->name('new');
	});

	Route::group(['prefix' => 'rules', 'as'=>'rules.'], function () {
		Route::get('all', 'AdminController@allRules')->name('all');
		Route::get('single/{id}/view', 'AdminController@singleRules')->name('single');
		Route::get('single/{id}/edit', 'AdminController@singleRulesEdit')->name('edit');
		Route::get('new', 'AdminController@createRules')->name('new');
	});

	Route::group(['prefix' => 'pages', 'as'=>'pages.'], function () {
		Route::get('homepage', 'AdminController@homepageSetings')->name('homepage');
		Route::get('about', 'AdminController@aboutSetings')->name('about');
		Route::get('generalsettings', 'AdminController@generalSettings')->name('generalsettings');
	});

});

Route::group(['prefix' => 'datatables', 'middleware' => ['auth', 'checkadmin' ], 'as'=>'datatables.'], function () {
	Route::any('newusers', 'DatatableController@newusers')->name('newusers');
	Route::any('allusers', 'DatatableController@allusers')->name('allusers');
	Route::any('allpermisions', 'DatatableController@allpermisions')->name('allpermisions');
	Route::any('singlepermision/{id}', 'DatatableController@singlePermision')->name('singlepermision');
	Route::any('allprojects', 'DatatableController@allprojects')->name('allprojects');
	Route::any('allevents', 'DatatableController@allevents')->name('allevents');
	Route::any('allposts', 'DatatableController@allposts')->name('allposts');
	Route::any('allpaymentsreceived', 'DatatableController@allpaymentsreceived')->name('allpaymentsreceived');
	Route::any('allfaqs', 'DatatableController@allfaqs')->name('allfaqs');
	Route::any('allrules', 'DatatableController@allrules')->name('allrules');
	Route::any('testmonials', 'DatatableController@testmonials')->name('testmonials');
	Route::any('slider', 'DatatableController@settingSlider')->name('settingslider');
	Route::any('sponsors', 'DatatableController@settingSponsors')->name('sponsors');
	Route::any('founders', 'DatatableController@founders')->name('founders');
	Route::post('deleteslider', 'DatatableController@deleteSlider')->name('deleteslider');
	Route::post('deletesponsor', 'DatatableController@deleteSponsor')->name('deletesponsor');
	Route::post('deletetestmonial', 'DatatableController@deleteTestmonial')->name('deletetestmonial');
	Route::post('deletefounder', 'DatatableController@deleteFounder')->name('deletefounder');
});

Route::group(['prefix' => 'chartdata', 'middleware' => ['auth', 'checkadmin' ], 'as'=>'chartdata.'], function () {
	Route::any('usersvsmonth', 'ChartController@usersVsMonth')->name('usersvsmonth');
	Route::any('projectsvsmonth', 'ChartController@projectsVsmonth')->name('projectsvsmonth');
	Route::any('eventsvsmonth', 'ChartController@eventsVsmonth')->name('eventsvsmonth');
	Route::any('postsvsmonth', 'ChartController@postsVsmonth')->name('postsvsmonth');
});

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::get('createproject', 'HomeController@createproject')->name('createproject');
    Route::get('myproject/{id}/view', 'HomeController@viewproject')->name('myproject');
    Route::get('myproject/{id}/donations', 'HomeController@viewprojectdonations')->name('myprojectdonations');
    Route::get('myproject/{id}/messages', 'HomeController@viewprojectmessages')->name('myprojectmessages');
    Route::get('myproject/{id}/messages/{comment}', 'HomeController@viewprojectmessagescomments')->name('viewprojectmessagescomments');
    Route::get('myproject/{id}/settings', 'HomeController@viewprojectsettings')->name('myprojectsettings');
    Route::get('myproject/{id}/stats', 'HomeController@viewprojectstats')->name('myprojectstats');
    Route::get('myprojects', 'HomeController@viewprojects')->name('myprojects');
    Route::get('mycontributions', 'HomeController@mycontributions')->name('mycontributions');
    Route::get('mydonations', 'HomeController@mydonations')->name('mydonations');
    Route::get('mymessages', 'HomeController@mymessages')->name('mymessages');
    Route::group(['prefix' => 'profile', 'as'=>'profile.'], function () {
		Route::get('/', 'HomeController@myProfile')->name('index');
	});

	Route::group(['as'=>'dash.'], function () {
		Route::get('transactions', 'HomeController@myTransactions')->name('transactions');
		Route::get('membership', 'HomeController@myMembership')->name('membership');
		Route::get('commisions', 'HomeController@myCommisions')->name('commisions');
		Route::get('banking', 'HomeController@myBanking')->name('banking');
	});

	Route::group(['prefix' => 'chartdata', 'as'=>'analytics.'], function () {
		Route::any('donationsvsmonth/{id}', 'ChartController@donationsVsmonth')->name('donations');
	});

});

Route::get('projects/{id}/messages', 'ProjectController@projectmessages')->name('projectmessages');
// Route::get('projects/{id}/donations', 'ProjectController@projectdonations')->name('projectdonations');
Route::any('mailboxes/{id}/sent', 'MailboxController@sentmail')->name('mailboxes.sentmail');
Route::any('mailboxes/{id}/inbox', 'MailboxController@inboxmail')->name('mailboxes.inboxmail');

Route::resource('photos', 'ImageController');

resources/views/layouts/admindashheader.blade.php
<ul>
  <li class="link  " ><a href="" ><span class="icon"><i class="fa fa-list"></i></span> <span>Projects Manager</span></a></li>
  <li class="link "><a href="" ><span class="icon"><i class="fa fa-heart"></i></span> <span>Finance Manager</span></a></li>
  <li class="link "><a href="" ><span class="icon"><i class="fa fa-th"></i></span> <span>Permission Manager</span></a></li>
  <li class="link"><a><span class="icon"><i class="fa fa-bookmark"></i></span> <span> Settings</span></a></li>
</ul>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>Infinity Investment Club - @yield('title')</title>
  <link rel="stylesheet" href="{{ asset('css/font-awesome.min.css') }}">
  <link rel="stylesheet"  href="{{ mix('css/app.css') }}" >
  <link rel="stylesheet"  href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" >
  @stack('header-css')
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" ></script>
  @stack('header-scripts')
</head>
<body>

@include('layouts.header')

@yield('content')

@include('layouts.footer')

<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<script src="{{ mix('js/app.js') }}"></script>

@stack('scripts')



</body>
</html>

resources/views/layouts/dashheader.blade.php
<ul>
  <li class="link {{{ (Route::is('myprojects') ? 'is-active' : '') }}} " ><a href="{{ route('myprojects')}}" ><span class="icon"><i class="fa fa-list"></i></span> <span>Projects</span></a></li>
  {{--<li class="link {{{ (Route::is('mycontributions') ? 'is-active' : '') }}} "><a href="{{ route('mycontributions')}}" ><span class="icon"><i class="fa fa-heart"></i></span> <span>Transactions</span></a></li> --}}
  <li class="link {{{ (Route::is('mymessages') ? 'is-active' : '') }}} "><a href="{{ route('mymessages')}}" ><span class="icon"><i class="fa fa-th"></i></span> <span>Mailbox</span></a></li>
  <li class="link {{{ (Route::is('profile.index') ? 'is-active' : '') }}} "><a href="{{ route('profile.index')}}" ><span class="icon"><i class="fa fa-user-o"></i></span> <span> Profile</span></a></li>
  <li class="link {{{ (Route::is('dash.transactions') ? 'is-active' : '') }}} "><a href="{{ route('dash.transactions')}}" ><span class="icon"><i class="fa fa-heart"></i></span> <span> Transactions</span></a></li>
  <li class="link {{{ (Route::is('dash.membership') ? 'is-active' : '') }}} "><a href="{{ route('dash.membership')}}" ><span class="icon"><i class="fa fa-bookmark"></i></span> <span> Membership</span></a></li>
  <li class="link {{{ (Route::is('dash.commisions') ? 'is-active' : '') }}} "><a href="{{ route('dash.commisions')}}" ><span class="icon"><i class="fa fa-money"></i></span> <span> Commisions</span></a></li>
  <li class="link {{{ (Route::is('dash.banking') ? 'is-active' : '') }}} "><a href="{{ route('dash.banking')}}" ><span class="icon"><i class="fa fa-bank"></i></span> <span> Banking</span></a></li>
</ul>

resources/views/layouts/footer.blade.php
<footer class="footer p-b-3 is-dark">
 <div class=" columns">
	<div class="column">
		<figure class="image is-2by3">
		   <img src="{{ asset('images/logo.jpeg') }}" >
		</figure>

		<p class="is-bold"><strong>Mission</strong></p>
		<p>
			To create a community that fosters investment culture for financial freedom
		</p>
		<p class="is-bold"><strong>Vision</strong></p>
		<p>
			To raise billionaire investors with global impact
             Mission: To create a community that fosters investment culture for financial freedom
		</p>
		<p class="is-bold"><strong>Motto</strong></p>
		<p>
			IIClub, Impactful Billionaires
Core Values: Integrity, Savings, Networking, Discipline, Fun, Profitability, Motivation, Mutual respect
		</p>

		<ul class="soc">
			<li><a target="_blank"   class="soc-twitter" href="{{ $social_links_setting->twitter }}" ></a></li>
			<li><a target="_blank"  class="soc-facebook" href="{{ $social_links_setting->facebook }}" ></a></li>
			<li><a target="_blank" class="soc-instagram soc-icon-last" href="{{ $social_links_setting->instagram }}" ></a></li>
		</ul>
	</div>
	<div class="column">
	   <div class="content">
		<p class=""><strong>Resent Blog Posts</strong></p>
			@forelse ($footer_blog_posts as $post)
			   @include('partials.postsinglefooter', ['post' => $post])
			@empty

			@endforelse
		</div>
		<p class=""><strong>Useful Links</strong></h5>
		<p>
		  <a href="{{ route('home')}}">Home</a> |
		  <a href="{{ route('about')}}">About us</a> |
		  <a href="{{ route('rules.index')}}">Rules</a> |
		  <a href="{{ route('faqs.index')}}">Faq's</a> |
		  <a href="{{ route('contacts')}}">Contact</a>
		</p>
	</div>
	<div class="column">
	  <div class=" columns">
	    <div class=" column is-10 is-offset-1">
			<div class="field">
			  <label class="label">Email </label>
			  <p class="control has-icons-left has-icons-right">
				<input class="input  is-hovered" id="footer_email" name="footer_email" type="email" placeholder="Email">
				<span class="icon is-small is-left">
				  <i class="fa fa-envelope"></i>
				</span>
			  </p>
			</div>
			<div class="field">
			  <label class="label">Password </label>
			  <p class="control has-icons-left has-icons-right">
				<input class="input  is-hovered" id="footer_password" name="footer_password" type="password" placeholder="****">
				<span class="icon is-small is-left">
				  <i class="fa fa-lock"></i>
				</span>
			  </p>
			</div>
			<div class="field">
			  <p class="control">
				<label class="checkbox">
				  <input type="checkbox">
				   Remember Me
				</label>
			  </p>
			</div>
			<div class="field is-grouped">
			  <p class="control">
				<button class="button is-primary">Login</button>
			  </p>
			  <p class="control">
				<button class="button is-link">Register</button>
			  </p>
			</div>
		</div>
	  </div>
	</div>

  </div>
<div class="container">
<div class="content has-text-centered">
  <p>
	Copyright <strong> <a href="{{ route('home')}}">Infinity Investment Club</a></strong> 2017.
  </p>
</div>
</div>
</footer>

resources/views/layouts/header.blade.php
<div class="columns is-gapless is-paddingless is-marginless">
	<div class="column">
		<nav class="nav is-primary b-bt">
		  <div class="nav-left">
		    <div class="nav-item">
				<ul class="soc">
					<li><a  target="_blank"  class="soc-twitter" href="{{ $social_links_setting->twitter }}" ></a></li>
					<li><a target="_blank"  class="soc-facebook" href="{{ $social_links_setting->facebook }}" ></a></li>
					<li><a target="_blank"  class="soc-instagram soc-icon-last" href="{{ $social_links_setting->instagram }}" ></a></li>
				</ul>
			</div>
		  </div>

		  <div class="nav-right">
			<a  href="{{ route('faqs.index') }}" class="nav-item">
			  Faq
			</a>
			<a  href="{{ route('donations') }}" class="nav-item">
			  Donate
			</a>
			<a href="{{ route('rules.index') }}" class="nav-item">
			   Rules & Regulations
			</a>
			<div class="nav-item">
			  <div class="field is-grouped">
				  @if (Auth::check())
				    <p class="control">
					  <a href="{{ route('createproject') }}" class="button is-primary">
						<span>New Project</span>
					  </a>
					</p>
					<p class="control">
					  <a href="{{ route('logout') }}" class="button is-primary">
						<span class="icon">
						  <i class="fa fa-sign-out"></i>
						</span>
						<span>Logout</span>
					  </a>
					</p>

				  @else
					<p class="control">
					  <a href="{{ route('login') }}" class="button" >
						<span class="icon">
						  <i class="fa fa-sign-in"></i>
						</span>
						<span>Login</span>
					  </a>
					</p>
					<p class="control">
					  <a href="{{ route('join') }}" class="button is-primary">
						<span class="icon">
						  <i class="fa fa-user-plus"></i>
						</span>
						<span>Join</span>
					  </a>
					</p>
				  @endif


			  </div>
			</div>
		  </div>
		</nav>

	</div>
</div>

<header class="nav main-header  bg-warning  has-shadow">
  <div class="container">
	<div class="nav-left">
	  <a href="{{ route('home')}}" class="nav-item is-brand">
		 <img src="{{ asset('images/logo.jpeg') }}"  alt="Logo">
	  </a>
	</div>
	<span class="nav-toggle">
	  <span></span>
	  <span></span>
	  <span></span>
	</span>
	<div class="nav-right nav-menu">
	  @if (Auth::check())
	    @if (Auth::user()->is_admin)
	      <a href="{{ route('administrator.dashboard')}}" class="nav-item  {{{ (Request::is('administrator.dashboard') ? 'is-active' : '') }}}">Dashboard</a>
		@else
		  <a href="{{ route('dashboard')}}" class="nav-item  {{{ (Request::is('dashboard') ? 'is-active' : '') }}}">Dashboard</a>
		@endif
	  @endif
	  <a href="{{ route('home')}}" class="nav-item  {{{ (Request::is('/') ? 'is-active' : '') }}}">Home</a>
	  <a href="{{ route('about')}}" class="nav-item {{{ (Request::is('about') ? 'is-active' : '') }}}">About Us</a>
	  <a href="{{ route('projects.index')}}" class="nav-item {{{ (Request::is('projects.index') ? 'is-active' : '') }}}">Explore</a>
	  <a href="{{ route('blog.index')}}" class="nav-item {{{ (Request::is('blog.index') ? 'is-active' : '') }}}">Blog</a>
	  <a href="{{ route('events.index')}}" class="nav-item {{{ (Request::is('events.index') ? 'is-active' : '') }}}">Events</a>
	  <a href="{{ route('contacts')}}" class="nav-item {{{ (Request::is('contacts') ? 'is-active' : '') }}}">Contact</a>
	</div>
  </div>
</header>

resources/views/layouts/projecttab.blade.php
<ul>
	<li class=" {{{ (Route::is('myprojects') ? 'is-active' : '') }}} ">
	  <a href="{{ route('myproject', ['id' => $project-> id]) }}">
		<span class="icon is-small"><i class="fa fa-image"></i></span>
		<span>General Details</span>
	  </a>
	</li>
	<li class="  ">
	  <a href="">
		<span class="icon is-small"><i class="fa fa-music"></i></span>
		<span>Donations</span>
	  </a>
	</li>
	<li>
	  <a>
		<span class="icon is-small"><i class="fa fa-film"></i></span>
		<span>Messages</span>
	  </a>
	</li>
	<li>
	  <a>
		<span class="icon is-small"><i class="fa fa-file-text-o"></i></span>
		<span>Settings</span>
	  </a>
	</li>
	<li>
	  <a>
		<span class="icon is-small"><i class="fa fa-file-text-o"></i></span>
		<span>Stats</span>
	  </a>
	</li>

</ul>